using Terraria;
using Terraria.ID;
using Terraria.ModLoader;

namespace MerchantsPlus.NPCs
{
    class Guide : GlobalNPC
    {
        

        public override void GetChat(NPC npc, ref string chat)
        {
            if (npc.type != NPCID.Guide) return;
            if (!Config.merchantDialog) return;
            string message = ":)";
            if (!NPC.downedSlimeKing)
            {
                message = Utils.dialog(new string[] {
                    ModLoader.GetMod("RecipeBrowser") != null ? "Remember to set your recipe browser hotkey!" : "Did you know there is this great mod called recipe browser? You should try it out!",
                    ModLoader.GetMod("StartWithBase") != null ? "I love your autogenerated base. ;)" : "Check out StartWithBase, it's an amazing mod!",
                    ModLoader.GetMod("AlchemistNPC") != null ? "You have to kill the Eye of Cthulhu for any of the alchemist NPCs to spawn." : "I hear AlchemistNPC is a great mod!"
                    });
            }
            else {
                message = Main.LocalPlayer.HeldItem.damage > 0 ? "Wow! " + Main.LocalPlayer.HeldItem.damage + " damage? That's pretty good for a " + Main.LocalPlayer.HeldItem.Name + "!" : "Can I see your weapon?";
            }
            chat = message;
        }

        

        public override void TownNPCAttackProj(NPC npc, ref int projType, ref int attackDelay)
        {
            if (npc.type != NPCID.Guide) return;
            attackDelay = 1;
            projType = ProjectileID.WoodenArrowFriendly;
            if (NPC.downedSlimeKing)
            {
                projType = ProjectileID.FireArrow;
            }
            if (NPC.downedBoss1)
            {
                projType = ProjectileID.FrostburnArrow;
            }
            if (NPC.downedBoss2)
            {
                projType = ProjectileID.JestersArrow;
            }
            if (NPC.downedBoss3)
            {
                projType = ProjectileID.UnholyArrow;
            }
            if (Main.hardMode)
            {
                projType = ProjectileID.HellfireArrow;
            }
            if (Utils.downedMechBosses() == 3)
            {
                projType = ProjectileID.HolyArrow;
            }
            if (NPC.downedPlantBoss)
            {
                projType = ProjectileID.ChlorophyteArrow;
            }
            if (NPC.downedMoonlord)
            {
                projType = ProjectileID.MoonlordArrow;
            }
        }

        
    }
}
