using Terraria;
using Terraria.ID;
using Terraria.ModLoader;

namespace MerchantsPlus.NPCs
{
    class Guide : ModNPC
    {
        static string[] shopNames = { "Shop", "Msc" };
        static int shopCounter = 0;
        static string currentShop = shopNames[shopCounter];
        static short npcid = NPCID.Guide;

        public override string Texture
        {
            get
            {
                return "Terraria/NPC_" + npcid;
            }
        }

        public override bool Autoload(ref string name)
        {
            name = "Squire";
            return mod.Properties.Autoload;
        }

        public override void SetStaticDefaults()
        {
            //Main.npcFrameCount[npc.type] = Main.npcFrameCount[npcid];
            Main.npcFrameCount[npc.type] = Main.npcFrameCount[npcid];
            NPCID.Sets.ExtraFramesCount[npc.type] = NPCID.Sets.ExtraFramesCount[npcid];
            NPCID.Sets.AttackFrameCount[npc.type] = NPCID.Sets.AttackFrameCount[npcid];
            NPCID.Sets.DangerDetectRange[npc.type] = NPCID.Sets.DangerDetectRange[npcid];
            NPCID.Sets.AttackType[npc.type] = NPCID.Sets.AttackType[npcid];
            NPCID.Sets.AttackTime[npc.type] = NPCID.Sets.AttackTime[npcid];
            NPCID.Sets.AttackAverageChance[npc.type] = NPCID.Sets.AttackAverageChance[npcid];
            NPCID.Sets.HatOffsetY[npc.type] = NPCID.Sets.HatOffsetY[npcid];
        }

        public override void SetDefaults()
        {
            npc.townNPC = true;
            npc.friendly = true;
            npc.width = 18;
            npc.height = 40;
            npc.aiStyle = 7;
            npc.damage = 10;
            npc.defense = 15;
            npc.lifeMax = 300;
            npc.HitSound = SoundID.NPCHit1;
            npc.DeathSound = SoundID.NPCDeath1;
            npc.knockBackResist = 0.5f;
            animationType = npcid;
        }

        public override bool CanTownNPCSpawn(int numTownNPCs, int money)
        {
            return true;
        }


        public override string TownNPCName()
        {
            return "Valkyrienyanko";
        }

        public override string GetChat()
        {
            string message = ":)";
            if (!NPC.downedSlimeKing)
            {
                message = Utils.dialog(new string[] {
                    ModLoader.GetMod("RecipeBrowser") != null ? "Remember to set your recipe browser hotkey!" : "Did you know there is this great mod called recipe browser? You should try it out!",
                    ModLoader.GetMod("StartWithBase") != null ? "I love your autogenerated base. ;)" : "Check out StartWithBase, it's an amazing mod!",
                    ModLoader.GetMod("AlchemistNPC") != null ? "You have to kill the Eye of Cthulhu for any of the alchemist NPCs to spawn." : "I hear AlchemistNPC is a great mod!"
                    });
            }
            else {
                message = Main.LocalPlayer.HeldItem.damage > 0 ? "Wow, " + Main.LocalPlayer.HeldItem.damage + " damage is pretty good for a " + Main.LocalPlayer.HeldItem.Name + "!" : "Hmm..";
            }
            return message;
        }

        public override void SetChatButtons(ref string button, ref string button2)
        {
            button = currentShop;
            button2 = "Cycle Shop";
        }

        public override void OnChatButtonClicked(bool firstButton, ref bool shop)
        {
            if (firstButton)
            {
                shop = true;
            }
            else
            {
                if (shopCounter >= shopNames.Length - 1)
                {
                    currentShop = shopNames[0];
                    shopCounter = 0;
                }
                else
                {
                    currentShop = shopNames[++shopCounter];
                }
                
            }
        }

        public override void SetupShop(Chest shop, ref int nextSlot)
        {
            switch (currentShop) {
                case "Msc":
                    shop.item[nextSlot++].SetDefaults(ItemID.Cannon);
                    shop.item[nextSlot++].SetDefaults(ItemID.Cannonball);
                    break;
                default:
                    shop.item[nextSlot++].SetDefaults(ItemID.CordageGuide);
                    if (Utils.isNPCHere(NPCID.Merchant)) {
                        shop.item[nextSlot++].SetDefaults(ItemID.Torch);
                        shop.item[nextSlot++].SetDefaults(ItemID.WoodenArrow); 
                    }
                    if (Utils.isNPCHere(NPCID.ArmsDealer)) shop.item[nextSlot++].SetDefaults(ItemID.MusketBall);
                    if (NPC.downedBoss3 && !Main.hardMode) { 
                        shop.item[nextSlot].SetDefaults(ItemID.ObsidianSkinPotion);
                        shop.item[nextSlot++].shopCustomPrice = MerchantsPlus.universalPotionCost;
                        shop.item[nextSlot++].SetDefaults(ItemID.GuideVoodooDoll);
                    }
                    break;
            }
        }

        public override void NPCLoot()
        {
            // Item.NewItem(npc.getRect(), ItemID.SlimeBanner);
        }

        public override void TownNPCAttackProj(ref int projType, ref int attackDelay)
        {
            attackDelay = 1;
            projType = ProjectileID.WoodenArrowFriendly;
            if (NPC.downedSlimeKing)
            {
                projType = ProjectileID.FlamingArrow;
            }
            if (NPC.downedBoss1)
            {
                projType = ProjectileID.FrostburnArrow;
            }
            if (NPC.downedBoss2)
            {
                projType = ProjectileID.JestersArrow;
            }
            if (Main.hardMode)
            {
                projType = ProjectileID.UnholyArrow;
            }
            if (Utils.downedMechBosses() == 1)
            {
                projType = ProjectileID.HolyArrow;
            }
            if (Utils.downedMechBosses() == 2)
            {
                projType = ProjectileID.CursedArrow;
            }
            if (Utils.downedMechBosses() == 3)
            {
                projType = ProjectileID.VenomArrow;
            }
            if (NPC.downedPlantBoss)
            {
                projType = ProjectileID.ChlorophyteArrow;
            }
            if (NPC.downedMoonlord)
            {
                projType = ProjectileID.MoonlordArrow;
            }
        }

        public override void TownNPCAttackStrength(ref int damage, ref float knockback)
        {
            damage = 20;
            knockback = 4f;
        }

        public override void TownNPCAttackCooldown(ref int cooldown, ref int randExtraCooldown)
        {
            cooldown = 0;
        }

        public override void TownNPCAttackProjSpeed(ref float multiplier, ref float gravityCorrection, ref float randomOffset)
        {
            multiplier = 12f;
            randomOffset = 2f;
        }
    }
}
